site_name: Flamingo Documentations
extra:
  logo: assets/flamingo-icon.png
extra_css:
  - stylesheets/ci.css
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - extra
  - footnotes
  - abbr
use_directory_urls: false
theme:
  name: 'material'
  favicon: assets/flamingo_head_black.png
#  custom_dir: 'theme'
  logo: assets/flamingo-small-icon.png

google_analytics:
  - UA-129655449-1
  - auto
